[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.2"

[features]
seeds = false
skip-lint = false
[programs.localnet]
perpetuals = "GAe535anCWR3h4fD1idNcUgrqfPqVbkDAjkt12U5DpNQ"
[programs.devnet]
perpetuals = "GAe535anCWR3h4fD1idNcUgrqfPqVbkDAjkt12U5DpNQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/perpetuals/tests/anchor/*.ts"
